# EDL Full Experiment (auto-parallel, per-(dataset,model) hyperparams)

10-fold cross-validation comparison of 8 LDL models across the datasets
listed in `DATASETS`, parallelised via `loky`. The pool config is
auto-detected by `edl_workers.auto_pool_config()`:

- **GPU mode** if ≥ 2 CUDA GPUs are visible to `nvidia-smi` — one worker
  pinned per GPU.
- **CPU mode** otherwise — a small number of fat CPU workers (≈
  `cpu_count // 4`).

The training loop lives in `edl_workers.py` next to this notebook so loky
subprocesses can `import edl_workers` cleanly. TensorFlow is imported
lazily inside each worker after `CUDA_VISIBLE_DEVICES` is pinned.

For each (model, dataset) pair we record six distributional metrics
(`chebyshev`, `clark`, `canberra`, `kl_divergence`, `cosine`,
`intersection`) across 10 folds, plus per-sample uncertainty for the
evidential / SNEFY models.

Hyperparameters are configured per-(dataset, model) in the **Hyperparams**
section below. Anything you don't override falls back to `DEFAULT_HP`.

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import importlib
import sys
import multiprocessing as mp
from collections import defaultdict
from concurrent.futures import as_completed
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from loky import get_reusable_executor

# Make edl_workers importable whether the kernel started in `demo/` or in the
# project root.
_demo_dir = Path.cwd() if (Path.cwd() / 'edl_workers.py').exists() else Path.cwd() / 'demo'
if str(_demo_dir) not in sys.path:
    sys.path.insert(0, str(_demo_dir))

import pyldl.utils
import pyldl.algorithms
importlib.reload(pyldl.utils)
importlib.reload(pyldl.algorithms)

from pyldl.utils import load_dataset
from edl_workers import (
    init_worker, run_one_fold, auto_pool_config,
    MODEL_NAMES, METRICS, DEFAULT_HP,
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403620.708517 2327698 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403620.712596 2327698 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403620.725282 2327698 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403620.725305 2327698 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403620.725307 2327698 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403620.725308 2327698 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

## Datasets and CV settings

In [2]:
DATASETS     = ['SJAFFE', 'SBU_3DFE', 'Movie']
N_SPLITS     = 10
RANDOM_STATE = 0

## Hyperparams

`DEFAULT_HP` (defined in `edl_workers.py`) supplies the fallback for any
key that isn't overridden:

```
n_hidden       64       # dense width for the encoder/MLP
learning_rate  1e-3     # AdamW; set to None to use each model's own optimizer
weight_decay   1e-4     # AdamW
dropout_rate   0.0      # inserted between hidden and output if > 0
epochs         2500     # upper bound; early stopping cuts it short
batch_size     None     # None → each model's own default
val_fraction   0.1      # of the training fold; held out as inner-val for early-stop
patience       50       # LDLEarlyStopping; set None to disable
minimum        100      # LDLEarlyStopping; minimum epochs before early-stop can fire
max_iterations 50       # SA_BFGS only
```

Override per (dataset, model) in `PER_DATASET_HP` below. Anything you
don't list uses `DEFAULT_HP` as-is.

In [3]:
PER_DATASET_HP = {
    'SJAFFE': {
        'AA_BP':                    {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'Duo_LDL':                  {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'EDL_LDL (loglikelihood)':  {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'EDL_LDL (bayes_mse)':      {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'BEDL_LDL (loglikelihood)': {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'BEDL_LDL (bayes_mse)':     {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'SNEFY_LDL':                {'patience': 100, 'minimum': 100, 'n_hidden': 64},
        'SA_BFGS':                  {},
    },
    'SBU_3DFE': {
        'AA_BP':                    {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'Duo_LDL':                  {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'EDL_LDL (loglikelihood)':  {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'EDL_LDL (bayes_mse)':      {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'BEDL_LDL (loglikelihood)': {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'BEDL_LDL (bayes_mse)':     {'patience': 20, 'minimum': 20, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'SNEFY_LDL':                {'patience': 100, 'minimum': 100, 'n_hidden': 32, 'weight_decay': 1e-4, 'batch_size': 256},
        'SA_BFGS':                  {},
    },
    'Natural_Scene': {
        'AA_BP':                    {},
        'Duo_LDL':                  {},
        'EDL_LDL (loglikelihood)':  {},
        'EDL_LDL (bayes_mse)':      {},
        'BEDL_LDL (loglikelihood)': {},
        'BEDL_LDL (bayes_mse)':     {},
        'SNEFY_LDL':                {},
        'SA_BFGS':                  {},
    },
    'Movie': {
        'AA_BP':                    {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'Duo_LDL':                  {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'EDL_LDL (loglikelihood)':  {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'EDL_LDL (bayes_mse)':      {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'BEDL_LDL (loglikelihood)': {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'BEDL_LDL (bayes_mse)':     {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'SNEFY_LDL':                {'patience': 20, 'minimum': 20, 'n_hidden': 4, 'weight_decay': 1e-3, 'batch_size': 512},
        'SA_BFGS':                  {},
    },
}


def resolve_hp(dataset, model_name):
    """Merge DEFAULT_HP with the per-(dataset, model) overrides."""
    hp = dict(DEFAULT_HP)
    hp.update(PER_DATASET_HP.get(dataset, {}).get(model_name, {}))
    return hp

## Pool configuration (auto-detected)

In [16]:
# Set POOL_CFG to a dict to override; leave None for auto-detect.
POOL_CFG = None
if POOL_CFG is None:
    POOL_CFG = auto_pool_config()

GPU_IDS   = POOL_CFG['gpu_ids']
N_WORKERS = POOL_CFG['n_workers']
INTRA     = POOL_CFG['intra_op_threads']
INTER     = POOL_CFG['inter_op_threads']
MODE      = POOL_CFG['mode']

print(f'mode      : {MODE}')
print(f'workers   : {N_WORKERS}')
print(f'gpu_ids   : {GPU_IDS if GPU_IDS else "(CPU only)"}')
print(f'tf threads: intra={INTRA}, inter={INTER}')

mode      : GPU
workers   : 3
gpu_ids   : [0, 1, 2]
tf threads: intra=1, inter=1

## Build the worker pool

In [5]:
mgr = mp.Manager()
gpu_queue = mgr.Queue()

slots = list(GPU_IDS) if GPU_IDS else [None] * N_WORKERS
assert len(slots) == N_WORKERS, 'one queue slot per worker'
for g in slots:
    gpu_queue.put(g)

executor = get_reusable_executor(
    max_workers=N_WORKERS,
    initializer=init_worker,
    initargs=(gpu_queue, INTRA, INTER),
    reuse=False,
)
print(f'pool ready: {N_WORKERS} workers, slots={slots}')

pool ready: 3 workers, slots=[0, 1, 2]

## Sanity check: what do the workers actually see?

`gpu_devices` should match what you expect for the mode:

- **GPU mode**: each worker has a different `CUDA_VISIBLE_DEVICES` and
  reports a single GPU device.
- **CPU mode**: every worker reports `CUDA_VISIBLE_DEVICES = '-1'` and
  an empty `gpu_devices` list.

In [6]:
def _check():
    import os, tensorflow as tf
    return {
        'pid': os.getpid(),
        'CUDA_VISIBLE_DEVICES': os.environ.get('CUDA_VISIBLE_DEVICES'),
        'gpu_devices': [d.name for d in tf.config.list_physical_devices('GPU')],
        'intra_threads': tf.config.threading.get_intra_op_parallelism_threads(),
        'inter_threads': tf.config.threading.get_inter_op_parallelism_threads(),
    }

checks = [executor.submit(_check) for _ in range(N_WORKERS * 4)]
df = pd.DataFrame([c.result() for c in checks]).drop_duplicates(subset='pid').reset_index(drop=True)
print(f'{len(df)} unique workers (expected {N_WORKERS})')
df

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403834.981793 2328440 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403834.985811 2328440 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403834.991258 2328442 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403834.995352 2328442 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403835.007320 2328440 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.007341 2328440 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.007343 2328440 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.007345 2328440 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.008142 2328442 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.008200 2328442 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.008228 2328442 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.008256 2328442 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403835.035652 2328441 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403835.039855 2328441 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403835.052148 2328441 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.052248 2328441 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.052278 2328441 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403835.052301 2328441 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

3 unique workers (expected 3)

,pid,CUDA_VISIBLE_DEVICES,gpu_devices,intra_threads,inter_threads
0,2328442,1,[/physical_device:GPU:0],1,1
1,2328441,2,[/physical_device:GPU:0],1,1
2,2328440,0,[/physical_device:GPU:0],1,1

## Build the job list

Each job carries the resolved `hp` dict for its (dataset, model)
combination, so workers don't need to know about `PER_DATASET_HP`.

In [7]:
jobs = []
for dataset_name in DATASETS:
    X, D = load_dataset(dataset_name, dir='dataset')
    print(f'{dataset_name}: {X.shape[0]} samples, {X.shape[1]} features, {D.shape[1]} labels')
    kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    for fold_idx, (train_idx, test_idx) in enumerate(kf.split(X), start=1):
        Xtr, Xte = X[train_idx], X[test_idx]
        Dtr, Dte = D[train_idx], D[test_idx]
        for model_name in MODEL_NAMES:
            hp = resolve_hp(dataset_name, model_name)
            jobs.append((dataset_name, model_name, fold_idx, Xtr, Dtr, Xte, Dte, hp))

total = len(jobs)
print(f'queued {total} jobs ({len(DATASETS)} datasets × {N_SPLITS} folds × {len(MODEL_NAMES)} models)')

SJAFFE: 213 samples, 243 features, 6 labels
SBU_3DFE: 2500 samples, 243 features, 6 labels
Movie: 7755 samples, 1869 features, 5 labels
queued 240 jobs (3 datasets × 10 folds × 8 models)

### Inspect the resolved hyperparams

Confirm the config you'll actually run with — defaults plus your
per-(dataset, model) overrides.

In [8]:
hp_rows = []
for ds in DATASETS:
    for m in MODEL_NAMES:
        hp = resolve_hp(ds, m)
        hp_rows.append({'dataset': ds, 'model': m, **hp})
hp_table = pd.DataFrame(hp_rows).set_index(['dataset', 'model'])
hp_table

                                   n_hidden  learning_rate  weight_decay  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)         64          0.001        0.0001
         EDL_LDL (bayes_mse)             64          0.001        0.0001
         BEDL_LDL (loglikelihood)        64          0.001        0.0001
         BEDL_LDL (bayes_mse)            64          0.001        0.0001
         Duo_LDL                         64          0.001        0.0001
         AA_BP                           64          0.001        0.0001
         SNEFY_LDL                       64          0.001        0.0001
         SA_BFGS                         64          0.001        0.0001
SBU_3DFE EDL_LDL (loglikelihood)         32          0.001        0.0001
         EDL_LDL (bayes_mse)             32          0.001        0.0001
         BEDL_LDL (loglikelihood)        32          0.001        0.0001
         BEDL_LDL (bayes_mse)            32          0.001        0.0001
         Duo_LDL                         32          0.001        0.0001
         AA_BP                           32          0.001        0.0001
         SNEFY_LDL                       32          0.001        0.0001
         SA_BFGS                         64          0.001        0.0001
Movie    EDL_LDL (loglikelihood)          4          0.001        0.0010
         EDL_LDL (bayes_mse)              4          0.001        0.0010
         BEDL_LDL (loglikelihood)         4          0.001        0.0010
         BEDL_LDL (bayes_mse)             4          0.001        0.0010
         Duo_LDL                          4          0.001        0.0010
         AA_BP                            4          0.001        0.0010
         SNEFY_LDL                        4          0.001        0.0010
         SA_BFGS                         64          0.001        0.0001

                                   dropout_rate  epochs  batch_size  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)            0.2    2500         NaN
         EDL_LDL (bayes_mse)                0.2    2500         NaN
         BEDL_LDL (loglikelihood)           0.2    2500         NaN
         BEDL_LDL (bayes_mse)               0.2    2500         NaN
         Duo_LDL                            0.2    2500         NaN
         AA_BP                              0.2    2500         NaN
         SNEFY_LDL                          0.2    2500         NaN
         SA_BFGS                            0.2    2500         NaN
SBU_3DFE EDL_LDL (loglikelihood)            0.2    2500       256.0
         EDL_LDL (bayes_mse)                0.2    2500       256.0
         BEDL_LDL (loglikelihood)           0.2    2500       256.0
         BEDL_LDL (bayes_mse)               0.2    2500       256.0
         Duo_LDL                            0.2    2500       256.0
         AA_BP                              0.2    2500       256.0
         SNEFY_LDL                          0.2    2500       256.0
         SA_BFGS                            0.2    2500         NaN
Movie    EDL_LDL (loglikelihood)            0.2    2500       512.0
         EDL_LDL (bayes_mse)                0.2    2500       512.0
         BEDL_LDL (loglikelihood)           0.2    2500       512.0
         BEDL_LDL (bayes_mse)               0.2    2500       512.0
         Duo_LDL                            0.2    2500       512.0
         AA_BP                              0.2    2500       512.0
         SNEFY_LDL                          0.2    2500       512.0
         SA_BFGS                            0.2    2500         NaN

                                   val_fraction  patience  minimum  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)            0.1       100      100
         EDL_LDL (bayes_mse)                0.1       100      100
         BEDL_LDL (loglikelihood)           0.1       100      100
         BEDL_LDL (bayes_mse)               0.1       100      100
         Duo_LDL                            0.1       100      100
         AA_BP                              0.1       100      100
         SNEFY_LDL                          0.1       100      100
         SA_BFGS                            0.1       100      100
SBU_3DFE EDL_LDL (loglikelihood)            0.1        20       20
         EDL_LDL (bayes_mse)                0.1        20       20
         BEDL_LDL (loglikelihood)           0.1        20       20
         BEDL_LDL (bayes_mse)               0.1        20       20
         Duo_LDL                            0.1        20       20
         AA_BP                              0.1        20       20
         SNEFY_LDL                          0.1       100      100
         SA_BFGS                            0.1       100      100
Movie    EDL_LDL (loglikelihood)            0.1        20       20
         EDL_LDL (bayes_mse)                0.1        20       20
         BEDL_LDL (loglikelihood)           0.1        20       20
         BEDL_LDL (bayes_mse)               0.1        20       20
         Duo_LDL                            0.1        20       20
         AA_BP                              0.1        20       20
         SNEFY_LDL                          0.1        20       20
         SA_BFGS                            0.1       100      100

                                   max_iterations
dataset  model
SJAFFE   EDL_LDL (loglikelihood)               50
         EDL_LDL (bayes_mse)                   50
         BEDL_LDL (loglikelihood)              50
         BEDL_LDL (bayes_mse)                  50
         Duo_LDL                               50
         AA_BP                                 50
         SNEFY_LDL                             50
         SA_BFGS                               50
SBU_3DFE EDL_LDL (loglikelihood)               50
         EDL_LDL (bayes_mse)                   50
         BEDL_LDL (loglikelihood)              50
         BEDL_LDL (bayes_mse)                  50
         Duo_LDL                               50
         AA_BP                                 50
         SNEFY_LDL                             50
         SA_BFGS                               50
Movie    EDL_LDL (loglikelihood)               50
         EDL_LDL (bayes_mse)                   50
         BEDL_LDL (loglikelihood)              50
         BEDL_LDL (bayes_mse)                  50
         Duo_LDL                               50
         AA_BP                                 50
         SNEFY_LDL                             50
         SA_BFGS                               50

## Submit + collect

Submission is non-blocking; results stream back via `as_completed`. Per-fold
failures are caught and logged but don't stop the run.

In [9]:
futures = {
    executor.submit(run_one_fold, ds, m, fi, Xtr, Dtr, Xte, Dte, hp): (ds, m, fi)
    for (ds, m, fi, Xtr, Dtr, Xte, Dte, hp) in jobs
}

raw_results = []
failures = []
for i, fut in enumerate(as_completed(futures), start=1):
    ds, m, fi = futures[fut]
    try:
        raw_results.append(fut.result())
        status = 'ok'
    except Exception as e:
        failures.append((ds, m, fi, repr(e)))
        status = f'FAILED ({type(e).__name__}: {e})'
    print(f'[{i:4d}/{total}] {ds:12s} | fold {fi:2d} | {m:30s} {status}')

print(f'\ndone: {len(raw_results)} ok, {len(failures)} failed')

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403890.276325 2328545 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403890.280838 2328545 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403890.305322 2328545 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.305437 2328545 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.305468 2328545 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.305492 2328545 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403890.349351 2328548 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403890.354631 2328548 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403890.377722 2328548 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.377739 2328548 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.377741 2328548 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.377743 2328548 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777403890.380099 2328546 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777403890.384182 2328546 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777403890.396443 2328546 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.396522 2328546 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.396552 2328546 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777403890.396575 2328546 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777403903.454689 2328548 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0
I0000 00:00:1777403903.454699 2328546 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:4c:00.0, compute capability: 9.0
I0000 00:00:1777403903.455049 2328545 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[   1/240] SJAFFE       | fold  1 | EDL_LDL (loglikelihood)        ok
[   2/240] SJAFFE       | fold  1 | BEDL_LDL (loglikelihood)       ok
[   3/240] SJAFFE       | fold  1 | EDL_LDL (bayes_mse)            ok
[   4/240] SJAFFE       | fold  1 | BEDL_LDL (bayes_mse)           ok
[   5/240] SJAFFE       | fold  1 | AA_BP                          ok
[   6/240] SJAFFE       | fold  1 | SA_BFGS                        ok
[   7/240] SJAFFE       | fold  1 | Duo_LDL                        ok
[   8/240] SJAFFE       | fold  2 | EDL_LDL (loglikelihood)        ok
[   9/240] SJAFFE       | fold  2 | BEDL_LDL (loglikelihood)       ok
[  10/240] SJAFFE       | fold  2 | EDL_LDL (bayes_mse)            ok
[  11/240] SJAFFE       | fold  2 | BEDL_LDL (bayes_mse)           ok
[  12/240] SJAFFE       | fold  1 | SNEFY_LDL                      ok
[  13/240] SJAFFE       | fold  2 | AA_BP                          ok
[  14/240] SJAFFE       | fold  2 | SA_BFGS                        ok
[  15/240] SJAFFE       | fold  2 | Duo_LDL                        ok
[  16/240] SJAFFE       | fold  3 | EDL_LDL (loglikelihood)        ok
[  17/240] SJAFFE       | fold  3 | EDL_LDL (bayes_mse)            ok
[  18/240] SJAFFE       | fold  3 | BEDL_LDL (loglikelihood)       ok
[  19/240] SJAFFE       | fold  3 | BEDL_LDL (bayes_mse)           ok
[  20/240] SJAFFE       | fold  3 | AA_BP                          ok
[  21/240] SJAFFE       | fold  3 | Duo_LDL                        ok
[  22/240] SJAFFE       | fold  3 | SA_BFGS                        ok
[  23/240] SJAFFE       | fold  2 | SNEFY_LDL                      ok
[  24/240] SJAFFE       | fold  4 | EDL_LDL (loglikelihood)        ok
[  25/240] SJAFFE       | fold  3 | SNEFY_LDL                      ok
[  26/240] SJAFFE       | fold  4 | EDL_LDL (bayes_mse)            ok
[  27/240] SJAFFE       | fold  4 | BEDL_LDL (bayes_mse)           ok
[  28/240] SJAFFE       | fold  4 | BEDL_LDL (loglikelihood)       ok
[  29/240] SJAFFE       | fold  4 | AA_BP                          ok
[  30/240] SJAFFE       | fold  4 | SA_BFGS                        ok
[  31/240] SJAFFE       | fold  4 | Duo_LDL                        ok
[  32/240] SJAFFE       | fold  5 | EDL_LDL (loglikelihood)        ok
[  33/240] SJAFFE       | fold  5 | BEDL_LDL (loglikelihood)       ok
[  34/240] SJAFFE       | fold  5 | EDL_LDL (bayes_mse)            ok
[  35/240] SJAFFE       | fold  5 | BEDL_LDL (bayes_mse)           ok
[  36/240] SJAFFE       | fold  4 | SNEFY_LDL                      ok
[  37/240] SJAFFE       | fold  5 | AA_BP                          ok
[  38/240] SJAFFE       | fold  5 | SA_BFGS                        ok
[  39/240] SJAFFE       | fold  5 | Duo_LDL                        ok
[  40/240] SJAFFE       | fold  6 | EDL_LDL (bayes_mse)            ok
[  41/240] SJAFFE       | fold  5 | SNEFY_LDL                      ok
[  42/240] SJAFFE       | fold  6 | EDL_LDL (loglikelihood)        ok
[  43/240] SJAFFE       | fold  6 | Duo_LDL                        ok
[  44/240] SJAFFE       | fold  6 | AA_BP                          ok
[  45/240] SJAFFE       | fold  6 | BEDL_LDL (bayes_mse)           ok
[  46/240] SJAFFE       | fold  6 | SA_BFGS                        ok
[  47/240] SJAFFE       | fold  7 | EDL_LDL (loglikelihood)        ok
[  48/240] SJAFFE       | fold  7 | EDL_LDL (bayes_mse)            ok
[  49/240] SJAFFE       | fold  7 | BEDL_LDL (loglikelihood)       ok
[  50/240] SJAFFE       | fold  6 | SNEFY_LDL                      ok
[  51/240] SJAFFE       | fold  7 | BEDL_LDL (bayes_mse)           ok
[  52/240] SJAFFE       | fold  7 | Duo_LDL                        ok
[  53/240] SJAFFE       | fold  7 | AA_BP                          ok
[  54/240] SJAFFE       | fold  7 | SA_BFGS                        ok
[  55/240] SJAFFE       | fold  7 | SNEFY_LDL                      ok
[  56/240] SJAFFE       | fold  8 | EDL_LDL (bayes_mse)            ok
[  57/240] SJAFFE       | fold  8 | EDL_LDL (loglikelihood)        ok
[  58/240] SJAFFE       | fold  8 | BEDL_LDL (loglikelihood)       ok
[  59/240] SJAFFE       | fold  8 | BEDL_LDL (bayes_mse)           ok
[  60/240] SJAFFE       | fold  8 | Duo_LDL                        ok
[  61/240] SJAFFE       | fold  8 | AA_BP                          ok
[  62/240] SJAFFE       | fold  8 | SA_BFGS                        ok
[  63/240] SJAFFE       | fold  9 | EDL_LDL (loglikelihood)        ok
[  64/240] SJAFFE       | fold  6 | BEDL_LDL (loglikelihood)       ok
[  65/240] SJAFFE       | fold  9 | BEDL_LDL (loglikelihood)       ok
[  66/240] SJAFFE       | fold  9 | EDL_LDL (bayes_mse)            ok
[  67/240] SJAFFE       | fold  8 | SNEFY_LDL                      ok
[  68/240] SJAFFE       | fold  9 | BEDL_LDL (bayes_mse)           ok
[  69/240] SJAFFE       | fold  9 | AA_BP                          ok
[  70/240] SJAFFE       | fold  9 | SA_BFGS                        ok
[  71/240] SJAFFE       | fold  9 | Duo_LDL                        ok
[  72/240] SJAFFE       | fold 10 | EDL_LDL (loglikelihood)        ok
[  73/240] SJAFFE       | fold 10 | BEDL_LDL (loglikelihood)       ok
[  74/240] SJAFFE       | fold 10 | BEDL_LDL (bayes_mse)           ok
[  75/240] SJAFFE       | fold 10 | EDL_LDL (bayes_mse)            ok
[  76/240] SJAFFE       | fold 10 | AA_BP                          ok
[  77/240] SJAFFE       | fold  9 | SNEFY_LDL                      ok
[  78/240] SJAFFE       | fold 10 | SA_BFGS                        ok
[  79/240] SJAFFE       | fold 10 | Duo_LDL                        ok
[  80/240] SJAFFE       | fold 10 | SNEFY_LDL                      ok
[  81/240] SBU_3DFE     | fold  1 | EDL_LDL (loglikelihood)        ok
[  82/240] SBU_3DFE     | fold  1 | EDL_LDL (bayes_mse)            ok
[  83/240] SBU_3DFE     | fold  1 | Duo_LDL                        ok
[  84/240] SBU_3DFE     | fold  1 | AA_BP                          ok
[  85/240] SBU_3DFE     | fold  1 | BEDL_LDL (bayes_mse)           ok
[  86/240] SBU_3DFE     | fold  1 | SA_BFGS                        ok
[  87/240] SBU_3DFE     | fold  2 | EDL_LDL (loglikelihood)        ok
[  88/240] SBU_3DFE     | fold  1 | SNEFY_LDL                      ok
[  89/240] SBU_3DFE     | fold  2 | BEDL_LDL (loglikelihood)       ok
[  90/240] SBU_3DFE     | fold  2 | BEDL_LDL (bayes_mse)           ok
[  91/240] SBU_3DFE     | fold  2 | Duo_LDL                        ok
[  92/240] SBU_3DFE     | fold  2 | AA_BP                          ok
[  93/240] SBU_3DFE     | fold  2 | SNEFY_LDL                      ok
[  94/240] SBU_3DFE     | fold  2 | SA_BFGS                        ok
[  95/240] SBU_3DFE     | fold  3 | EDL_LDL (loglikelihood)        ok
[  96/240] SBU_3DFE     | fold  3 | EDL_LDL (bayes_mse)            ok
[  97/240] SBU_3DFE     | fold  2 | EDL_LDL (bayes_mse)            ok
[  98/240] SBU_3DFE     | fold  3 | BEDL_LDL (bayes_mse)           ok
[  99/240] SBU_3DFE     | fold  3 | Duo_LDL                        ok
[ 100/240] SBU_3DFE     | fold  3 | AA_BP                          ok
[ 101/240] SBU_3DFE     | fold  3 | SNEFY_LDL                      ok
[ 102/240] SBU_3DFE     | fold  3 | SA_BFGS                        ok
[ 103/240] SBU_3DFE     | fold  4 | EDL_LDL (loglikelihood)        ok
[ 104/240] SBU_3DFE     | fold  4 | EDL_LDL (bayes_mse)            ok
[ 105/240] SBU_3DFE     | fold  4 | BEDL_LDL (loglikelihood)       ok
[ 106/240] SBU_3DFE     | fold  4 | BEDL_LDL (bayes_mse)           ok
[ 107/240] SBU_3DFE     | fold  4 | Duo_LDL                        ok
[ 108/240] SBU_3DFE     | fold  4 | AA_BP                          ok
[ 109/240] SBU_3DFE     | fold  4 | SNEFY_LDL                      ok
[ 110/240] SBU_3DFE     | fold  4 | SA_BFGS                        ok
[ 111/240] SBU_3DFE     | fold  1 | BEDL_LDL (loglikelihood)       ok
[ 112/240] SBU_3DFE     | fold  5 | EDL_LDL (bayes_mse)            ok
[ 113/240] SBU_3DFE     | fold  5 | EDL_LDL (loglikelihood)        ok
[ 114/240] SBU_3DFE     | fold  5 | BEDL_LDL (bayes_mse)           ok
[ 115/240] SBU_3DFE     | fold  3 | BEDL_LDL (loglikelihood)       ok
[ 116/240] SBU_3DFE     | fold  5 | Duo_LDL                        ok
[ 117/240] SBU_3DFE     | fold  5 | AA_BP                          ok
[ 118/240] SBU_3DFE     | fold  5 | SA_BFGS                        ok
[ 119/240] SBU_3DFE     | fold  6 | EDL_LDL (loglikelihood)        ok
[ 120/240] SBU_3DFE     | fold  6 | EDL_LDL (bayes_mse)            ok
[ 121/240] SBU_3DFE     | fold  5 | SNEFY_LDL                      ok
[ 122/240] SBU_3DFE     | fold  6 | BEDL_LDL (bayes_mse)           ok
[ 123/240] SBU_3DFE     | fold  6 | Duo_LDL                        ok
[ 124/240] SBU_3DFE     | fold  6 | AA_BP                          ok
[ 125/240] SBU_3DFE     | fold  6 | SNEFY_LDL                      ok
[ 126/240] SBU_3DFE     | fold  6 | SA_BFGS                        ok
[ 127/240] SBU_3DFE     | fold  7 | EDL_LDL (loglikelihood)        ok
[ 128/240] SBU_3DFE     | fold  7 | EDL_LDL (bayes_mse)            ok
[ 129/240] SBU_3DFE     | fold  6 | BEDL_LDL (loglikelihood)       ok
[ 130/240] SBU_3DFE     | fold  7 | BEDL_LDL (bayes_mse)           ok
[ 131/240] SBU_3DFE     | fold  7 | Duo_LDL                        ok
[ 132/240] SBU_3DFE     | fold  7 | AA_BP                          ok
[ 133/240] SBU_3DFE     | fold  7 | SNEFY_LDL                      ok
[ 134/240] SBU_3DFE     | fold  7 | SA_BFGS                        ok
[ 135/240] SBU_3DFE     | fold  8 | EDL_LDL (loglikelihood)        ok
[ 136/240] SBU_3DFE     | fold  8 | EDL_LDL (bayes_mse)            ok
[ 137/240] SBU_3DFE     | fold  5 | BEDL_LDL (loglikelihood)       ok
[ 138/240] SBU_3DFE     | fold  8 | BEDL_LDL (bayes_mse)           ok
[ 139/240] SBU_3DFE     | fold  8 | Duo_LDL                        ok
[ 140/240] SBU_3DFE     | fold  8 | AA_BP                          ok
[ 141/240] SBU_3DFE     | fold  7 | BEDL_LDL (loglikelihood)       ok
[ 142/240] SBU_3DFE     | fold  8 | SA_BFGS                        ok
[ 143/240] SBU_3DFE     | fold  9 | EDL_LDL (loglikelihood)        ok
[ 144/240] SBU_3DFE     | fold  8 | SNEFY_LDL                      ok
[ 145/240] SBU_3DFE     | fold  9 | BEDL_LDL (loglikelihood)       ok
[ 146/240] SBU_3DFE     | fold  9 | EDL_LDL (bayes_mse)            ok
[ 147/240] SBU_3DFE     | fold  9 | Duo_LDL                        ok
[ 148/240] SBU_3DFE     | fold  9 | AA_BP                          ok
[ 149/240] SBU_3DFE     | fold  9 | BEDL_LDL (bayes_mse)           ok
[ 150/240] SBU_3DFE     | fold  9 | SA_BFGS                        ok
[ 151/240] SBU_3DFE     | fold 10 | EDL_LDL (loglikelihood)        ok
[ 152/240] SBU_3DFE     | fold  9 | SNEFY_LDL                      ok
[ 153/240] SBU_3DFE     | fold  8 | BEDL_LDL (loglikelihood)       ok
[ 154/240] SBU_3DFE     | fold 10 | BEDL_LDL (bayes_mse)           ok
[ 155/240] SBU_3DFE     | fold 10 | Duo_LDL                        ok
[ 156/240] SBU_3DFE     | fold 10 | AA_BP                          ok
[ 157/240] SBU_3DFE     | fold 10 | SNEFY_LDL                      ok
[ 158/240] SBU_3DFE     | fold 10 | SA_BFGS                        ok
[ 159/240] SBU_3DFE     | fold 10 | EDL_LDL (bayes_mse)            ok
[ 160/240] Movie        | fold  1 | EDL_LDL (loglikelihood)        ok
[ 161/240] Movie        | fold  1 | BEDL_LDL (loglikelihood)       ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405353.011761 2450436 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405353.017785 2450436 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405353.030198 2450436 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405353.030295 2450436 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405353.030331 2450436 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405353.030360 2450436 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405362.769167 2450436 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7894 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[ 162/240] SBU_3DFE     | fold 10 | BEDL_LDL (loglikelihood)       ok
[ 163/240] Movie        | fold  1 | EDL_LDL (bayes_mse)            ok
[ 164/240] Movie        | fold  1 | BEDL_LDL (bayes_mse)           ok
[ 165/240] Movie        | fold  1 | Duo_LDL                        ok
[ 166/240] Movie        | fold  1 | SA_BFGS                        ok
[ 167/240] Movie        | fold  1 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())
[ 168/240] Movie        | fold  1 | AA_BP                          ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405453.668672 2453799 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405453.673103 2453799 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405453.685499 2453799 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405453.685591 2453799 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405453.685621 2453799 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405453.685645 2453799 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

[ 169/240] Movie        | fold  2 | EDL_LDL (loglikelihood)        ok

/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405464.452866 2453799 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0

[ 170/240] Movie        | fold  2 | EDL_LDL (bayes_mse)            ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405470.277737 2454215 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405470.282220 2454215 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405470.294874 2454215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405470.294979 2454215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405470.295008 2454215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405470.295032 2454215 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405479.586485 2454215 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:4c:00.0, compute capability: 9.0

[ 171/240] Movie        | fold  2 | BEDL_LDL (loglikelihood)       ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405490.411482 2454699 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405490.415922 2454699 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405490.428271 2454699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405490.428391 2454699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405490.428421 2454699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405490.428463 2454699 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405499.944433 2454699 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[ 172/240] Movie        | fold  2 | Duo_LDL                        ok
[ 173/240] Movie        | fold  2 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())
[ 174/240] Movie        | fold  2 | SA_BFGS                        ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405541.506311 2456356 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405541.510756 2456356 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405541.549742 2456356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405541.551700 2456356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405541.555382 2456356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405541.555464 2456356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405551.780643 2456356 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7650 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0

[ 175/240] Movie        | fold  2 | BEDL_LDL (bayes_mse)           ok
[ 176/240] Movie        | fold  2 | AA_BP                          ok
[ 177/240] Movie        | fold  3 | EDL_LDL (loglikelihood)        ok
[ 178/240] Movie        | fold  3 | BEDL_LDL (loglikelihood)       ok
[ 179/240] Movie        | fold  3 | BEDL_LDL (bayes_mse)           ok
[ 180/240] Movie        | fold  3 | EDL_LDL (bayes_mse)            ok
[ 181/240] Movie        | fold  3 | Duo_LDL                        ok
[ 182/240] Movie        | fold  3 | SA_BFGS                        ok
[ 183/240] Movie        | fold  3 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405667.840969 2460425 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405667.857518 2460425 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405667.874933 2460425 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405667.875931 2460425 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405667.876014 2460425 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405667.876177 2460425 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405679.477075 2460425 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:4c:00.0, compute capability: 9.0

[ 184/240] Movie        | fold  3 | AA_BP                          ok
[ 185/240] Movie        | fold  4 | EDL_LDL (loglikelihood)        ok
[ 186/240] Movie        | fold  4 | EDL_LDL (bayes_mse)            ok
[ 187/240] Movie        | fold  4 | BEDL_LDL (bayes_mse)           ok
[ 188/240] Movie        | fold  4 | BEDL_LDL (loglikelihood)       ok
[ 189/240] Movie        | fold  4 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405784.732334 2464228 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405784.736744 2464228 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405784.758115 2464228 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405784.758280 2464228 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405784.758310 2464228 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405784.758334 2464228 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

[ 190/240] Movie        | fold  4 | Duo_LDL                        ok
[ 191/240] Movie        | fold  4 | SA_BFGS                        ok

I0000 00:00:1777405796.057760 2464228 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7650 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[ 192/240] Movie        | fold  5 | EDL_LDL (bayes_mse)            ok
[ 193/240] Movie        | fold  4 | AA_BP                          ok
[ 194/240] Movie        | fold  5 | EDL_LDL (loglikelihood)        ok
[ 195/240] Movie        | fold  5 | BEDL_LDL (bayes_mse)           ok
[ 196/240] Movie        | fold  5 | BEDL_LDL (loglikelihood)       ok
[ 197/240] Movie        | fold  5 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405880.662562 2467355 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405880.666912 2467355 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405880.681058 2467355 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405880.681183 2467355 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405880.681213 2467355 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405880.681237 2467355 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

[ 198/240] Movie        | fold  5 | SA_BFGS                        ok

I0000 00:00:1777405894.588329 2467355 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0

[ 199/240] Movie        | fold  5 | Duo_LDL                        ok
[ 200/240] Movie        | fold  6 | EDL_LDL (loglikelihood)        ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777405950.772551 2469780 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777405950.777217 2469780 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777405950.789971 2469780 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405950.790072 2469780 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405950.790101 2469780 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777405950.790124 2469780 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

[ 201/240] Movie        | fold  6 | EDL_LDL (bayes_mse)            ok

/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777405962.354740 2469780 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:4c:00.0, compute capability: 9.0

[ 202/240] Movie        | fold  5 | AA_BP                          ok
[ 203/240] Movie        | fold  6 | BEDL_LDL (loglikelihood)       ok
[ 204/240] Movie        | fold  6 | BEDL_LDL (bayes_mse)           ok
[ 205/240] Movie        | fold  6 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())
[ 206/240] Movie        | fold  6 | SA_BFGS                        ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777406013.720549 2473273 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777406013.724862 2473273 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777406013.737802 2473273 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406013.737902 2473273 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406013.737937 2473273 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406013.737962 2473273 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777406026.088794 2473273 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6971 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[ 207/240] Movie        | fold  6 | Duo_LDL                        ok
[ 208/240] Movie        | fold  6 | AA_BP                          ok
[ 209/240] Movie        | fold  7 | EDL_LDL (loglikelihood)        ok
[ 210/240] Movie        | fold  7 | BEDL_LDL (loglikelihood)       ok
[ 211/240] Movie        | fold  7 | BEDL_LDL (bayes_mse)           ok
[ 212/240] Movie        | fold  7 | EDL_LDL (bayes_mse)            ok
[ 213/240] Movie        | fold  7 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())
[ 214/240] Movie        | fold  7 | Duo_LDL                        ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777406162.705082 2478704 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777406162.709481 2478704 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777406162.721689 2478704 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406162.721801 2478704 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406162.721832 2478704 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406162.721856 2478704 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

[ 215/240] Movie        | fold  7 | SA_BFGS                        ok

/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777406172.206329 2478704 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0

[ 216/240] Movie        | fold  7 | AA_BP                          ok
[ 217/240] Movie        | fold  8 | EDL_LDL (loglikelihood)        ok
[ 218/240] Movie        | fold  8 | EDL_LDL (bayes_mse)            ok
[ 219/240] Movie        | fold  8 | BEDL_LDL (loglikelihood)       ok
[ 220/240] Movie        | fold  8 | BEDL_LDL (bayes_mse)           ok
[ 221/240] Movie        | fold  8 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777406260.435229 2481905 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777406260.439786 2481905 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777406260.452784 2481905 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406260.452881 2481905 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406260.452910 2481905 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406260.452934 2481905 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

[ 222/240] Movie        | fold  8 | Duo_LDL                        ok

/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

[ 223/240] Movie        | fold  8 | SA_BFGS                        ok

I0000 00:00:1777406270.676689 2481905 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:4c:00.0, compute capability: 9.0

[ 224/240] Movie        | fold  8 | AA_BP                          ok
[ 225/240] Movie        | fold  9 | EDL_LDL (bayes_mse)            ok
[ 226/240] Movie        | fold  9 | EDL_LDL (loglikelihood)        ok
[ 227/240] Movie        | fold  9 | BEDL_LDL (bayes_mse)           ok
[ 228/240] Movie        | fold  9 | BEDL_LDL (loglikelihood)       ok
[ 229/240] Movie        | fold  9 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777406344.318099 2484563 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777406344.323805 2484563 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777406344.336536 2484563 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406344.336639 2484563 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406344.336669 2484563 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406344.336694 2484563 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

[ 230/240] Movie        | fold  9 | SA_BFGS                        ok

I0000 00:00:1777406356.631466 2484563 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8074 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:06:00.0, compute capability: 9.0

[ 231/240] Movie        | fold  9 | Duo_LDL                        ok
[ 232/240] Movie        | fold  9 | AA_BP                          ok
[ 233/240] Movie        | fold 10 | EDL_LDL (loglikelihood)        ok

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777406412.432291 2486667 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777406412.436661 2486667 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777406412.448916 2486667 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406412.449010 2486667 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406412.449041 2486667 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777406412.449066 2486667 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

[ 234/240] Movie        | fold 10 | BEDL_LDL (loglikelihood)       ok

/home/dcs01/.local/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
I0000 00:00:1777406423.845090 2486667 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7650 MB memory:  -> device: 0, name: NVIDIA H100 80GB HBM3 MIG 1g.10gb, pci bus id: 0000:0c:00.0, compute capability: 9.0

[ 235/240] Movie        | fold 10 | EDL_LDL (bayes_mse)            ok
[ 236/240] Movie        | fold 10 | Duo_LDL                        ok
[ 237/240] Movie        | fold 10 | BEDL_LDL (bayes_mse)           ok
[ 238/240] Movie        | fold 10 | SA_BFGS                        ok
[ 239/240] Movie        | fold 10 | SNEFY_LDL                      FAILED (TypeError: object of type 'NoneType' has no len())
[ 240/240] Movie        | fold 10 | AA_BP                          ok

done: 230 ok, 10 failed

### Worker-state diagnostic

If the submit cell hangs, run this in a separate cell to see if any
workers have died. Healthy state = all workers `sleeping`/`running` with
non-trivial `rss`. Dead PIDs in the `dead` list = OOM-killed or crashed,
in which case rebuild the pool and resubmit only `missing` jobs.

In [ ]:
import psutil

worker_pids = list(executor._processes.keys())
alive, dead = [], []
for pid in worker_pids:
    try:
        p = psutil.Process(pid)
        if p.is_running() and p.status() != psutil.STATUS_ZOMBIE:
            alive.append((pid, p.status(), p.memory_info().rss / 1e9, p.cpu_percent(interval=0.5)))
        else:
            dead.append(pid)
    except psutil.NoSuchProcess:
        dead.append(pid)

print(f'alive workers ({len(alive)}/{N_WORKERS}):')
for pid, status, rss_gb, cpu in alive:
    print(f'  pid={pid}  status={status}  rss={rss_gb:.1f}GB  cpu={cpu:.0f}%')
print(f'dead workers: {dead}')
print(f'\nresults so far: {len(raw_results)} / {total}')
print(f'completed futures: {sum(f.done() for f in futures)}')
print(f'pending futures:   {sum(not f.done() for f in futures)}')

## Bucket results into per-model DataFrames

In [10]:
buckets = defaultdict(list)
for r in raw_results:
    buckets[(r['dataset'], r['model'])].append(r['scores'])

per_model_results = {key: pd.DataFrame(rows) for key, rows in buckets.items()}
print(f'{len(per_model_results)} (dataset, model) combinations have results')

23 (dataset, model) combinations have results

## Per-model fold tables

In [11]:
if per_model_results:
    first_key = next(iter(per_model_results))
    print(f'showing: {first_key}')
    display(per_model_results[first_key])
else:
    print('no results yet — run the submit cell first')

showing: ('SJAFFE', 'EDL_LDL (loglikelihood)')

,chebyshev,clark,canberra,kl_divergence,cosine,intersection,mean_uncertainty,uncertainty_calibration
0,0.138662,0.474765,1.022165,0.091973,0.913105,0.823461,0.589772,-0.189159
1,0.128364,0.457179,0.968833,0.079271,0.924308,0.834559,0.572139,0.555775
2,0.129258,0.438752,0.905251,0.078405,0.925533,0.844238,0.592153,-0.588933
3,0.114620,0.390878,0.813435,0.063263,0.938972,0.860259,0.346719,-0.112987
4,0.103143,0.430306,0.896292,0.065382,0.939984,0.852348,0.589863,-0.018182
5,0.124777,0.425657,0.901544,0.084081,0.923120,0.845267,0.168534,0.228571
6,0.119544,0.421769,0.887102,0.073684,0.931104,0.848716,0.589529,-0.149351
7,0.110321,0.413030,0.852734,0.064215,0.940094,0.857899,0.168397,-0.215584
8,0.114374,0.423489,0.887972,0.070165,0.933828,0.849907,0.587663,0.128571
9,0.113394,0.388088,0.831635,0.067054,0.935970,0.856179,0.584553,0.040260

## Combined summary — mean ± std across folds

In [12]:
def summarize(df):
    out = {}
    for col in df.columns:
        out[f'{col}_mean'] = df[col].mean()
        out[f'{col}_std']  = df[col].std()
    return out


summary_rows = []
for (dataset_name, model_name), df in per_model_results.items():
    if df.empty:
        continue
    row = {'dataset': dataset_name, 'model': model_name, **summarize(df)}
    summary_rows.append(row)

summary = pd.DataFrame(summary_rows).set_index(['dataset', 'model'])
summary

                                   chebyshev_mean  chebyshev_std  clark_mean  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)         0.119646       0.010582    0.426391
         BEDL_LDL (loglikelihood)        0.117727       0.011637    0.418165
         EDL_LDL (bayes_mse)             0.120396       0.009920    0.430536
         BEDL_LDL (bayes_mse)            0.120148       0.010074    0.429345
         AA_BP                           0.119290       0.011377    0.426552
         SA_BFGS                         0.087746       0.008730    0.326173
         Duo_LDL                         0.119538       0.011076    0.430547
         SNEFY_LDL                       0.144438       0.022902    0.554543
SBU_3DFE EDL_LDL (loglikelihood)         0.137306       0.002745    0.410570
         EDL_LDL (bayes_mse)             0.136437       0.003132    0.412252
         Duo_LDL                         0.134806       0.002396    0.417340
         AA_BP                           0.134981       0.002632    0.416889
         BEDL_LDL (bayes_mse)            0.135274       0.002866    0.414751
         SA_BFGS                         0.128959       0.002345    0.403880
         SNEFY_LDL                       0.187100       0.040790    0.717544
         BEDL_LDL (loglikelihood)        0.128580       0.005435    0.386926
Movie    EDL_LDL (loglikelihood)         0.116226       0.002676    0.525218
         BEDL_LDL (loglikelihood)        0.118012       0.002841    0.532703
         EDL_LDL (bayes_mse)             0.124058       0.004956    0.560412
         BEDL_LDL (bayes_mse)            0.118094       0.003039    0.535716
         Duo_LDL                         0.119404       0.003971    0.545104
         SA_BFGS                         0.145060       0.003879    0.586648
         AA_BP                           0.115334       0.003300    0.523317

                                   clark_std  canberra_mean  canberra_std  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)    0.026652       0.896696      0.061742
         BEDL_LDL (loglikelihood)   0.033509       0.876625      0.079071
         EDL_LDL (bayes_mse)        0.025678       0.900584      0.059238
         BEDL_LDL (bayes_mse)       0.027264       0.896823      0.065307
         AA_BP                      0.027539       0.889118      0.061249
         SA_BFGS                    0.027843       0.665279      0.053841
         Duo_LDL                    0.028214       0.896047      0.060517
         SNEFY_LDL                  0.112102       1.157216      0.232641
SBU_3DFE EDL_LDL (loglikelihood)    0.004402       0.896695      0.007651
         EDL_LDL (bayes_mse)        0.004507       0.898070      0.008817
         Duo_LDL                    0.004285       0.903614      0.007362
         AA_BP                      0.003586       0.903325      0.006202
         BEDL_LDL (bayes_mse)       0.004350       0.900090      0.009177
         SA_BFGS                    0.006497       0.863641      0.011503
         SNEFY_LDL                  0.207385       1.451091      0.383958
         BEDL_LDL (loglikelihood)   0.013746       0.841078      0.030613
Movie    EDL_LDL (loglikelihood)    0.011939       1.002495      0.021059
         BEDL_LDL (loglikelihood)   0.011205       1.016737      0.020579
         EDL_LDL (bayes_mse)        0.020337       1.065178      0.041605
         BEDL_LDL (bayes_mse)       0.011458       1.016957      0.021985
         Duo_LDL                    0.016733       1.036006      0.032592
         SA_BFGS                    0.009972       1.119303      0.017762
         AA_BP                      0.013723       0.999038      0.025506

                                   kl_divergence_mean  kl_divergence_std  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)             0.073749           0.009543
         BEDL_LDL (loglikelihood)            0.071332           0.010148
         EDL_LDL (bayes_mse)                 0.074028           0.008367
         BEDL_LDL (bayes_mse)                0.074017           0.008986
         AA_BP                               0.073691           0.011047
         SA_BFGS                             0.043152           0.008980
         Duo_LDL                             0.074072           0.009577
         SNEFY_LDL                           0.127378           0.046930
SBU_3DFE EDL_LDL (loglikelihood)             0.083704           0.001622
         EDL_LDL (bayes_mse)                 0.083683           0.002164
         Duo_LDL                             0.082783           0.001631
         AA_BP                               0.082828           0.001596
         BEDL_LDL (bayes_mse)                0.082800           0.001908
         SA_BFGS                             0.075924           0.001957
         SNEFY_LDL                           0.239374           0.141278
         BEDL_LDL (loglikelihood)            0.073835           0.005943
Movie    EDL_LDL (loglikelihood)             0.099515           0.003612
         BEDL_LDL (loglikelihood)            0.102382           0.004442
         EDL_LDL (bayes_mse)                 0.111276           0.009355
         BEDL_LDL (bayes_mse)                0.102434           0.004758
         Duo_LDL                             0.113782           0.010492
         SA_BFGS                             0.133075           0.004485
         AA_BP                               0.099250           0.004590

                                   cosine_mean  cosine_std  intersection_mean  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)      0.930602    0.008914           0.847283
         BEDL_LDL (loglikelihood)     0.932831    0.009871           0.850592
         EDL_LDL (bayes_mse)          0.930193    0.007821           0.846555
         BEDL_LDL (bayes_mse)         0.930255    0.008468           0.847202
         AA_BP                        0.930612    0.010233           0.848382
         SA_BFGS                      0.959386    0.008108           0.888177
         Duo_LDL                      0.930205    0.008932           0.847173
         SNEFY_LDL                    0.888753    0.036446           0.801677
SBU_3DFE EDL_LDL (loglikelihood)      0.918932    0.001568           0.839654
         EDL_LDL (bayes_mse)          0.918863    0.001977           0.839287
         Duo_LDL                      0.919359    0.001535           0.838095
         AA_BP                        0.919345    0.001560           0.838189
         BEDL_LDL (bayes_mse)         0.919456    0.001811           0.838837
         SA_BFGS                      0.925833    0.001804           0.845069
         SNEFY_LDL                    0.834852    0.055414           0.755457
         BEDL_LDL (loglikelihood)     0.927886    0.005466           0.849347
Movie    EDL_LDL (loglikelihood)      0.934482    0.001978           0.834804
         BEDL_LDL (loglikelihood)     0.932753    0.002657           0.832217
         EDL_LDL (bayes_mse)          0.927073    0.005624           0.823297
         BEDL_LDL (bayes_mse)         0.933014    0.002614           0.832318
         Duo_LDL                      0.931290    0.003857           0.829523
         SA_BFGS                      0.911512    0.002937           0.807424
         AA_BP                        0.934783    0.002587           0.835405

                                   intersection_std  mean_uncertainty_mean  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)           0.011242               0.478932
         BEDL_LDL (loglikelihood)          0.013766               0.332203
         EDL_LDL (bayes_mse)               0.010411               0.459290
         BEDL_LDL (bayes_mse)              0.011668               0.281466
         AA_BP                             0.011318                    NaN
         SA_BFGS                           0.008919                    NaN
         Duo_LDL                           0.010752                    NaN
         SNEFY_LDL                         0.040916               0.300787
SBU_3DFE EDL_LDL (loglikelihood)           0.001501               0.361611
         EDL_LDL (bayes_mse)               0.001731               0.310146
         Duo_LDL                           0.001404                    NaN
         AA_BP                             0.001326                    NaN
         BEDL_LDL (bayes_mse)              0.001810               0.030943
         SA_BFGS                           0.002051                    NaN
         SNEFY_LDL                         0.054190               0.241147
         BEDL_LDL (loglikelihood)          0.005500               0.165246
Movie    EDL_LDL (loglikelihood)           0.002819               0.283544
         BEDL_LDL (loglikelihood)          0.002925               0.236538
         EDL_LDL (bayes_mse)               0.007587               0.101602
         BEDL_LDL (bayes_mse)              0.003224               0.017554
         Duo_LDL                           0.005607                    NaN
         SA_BFGS                           0.003271                    NaN
         AA_BP                             0.003819                    NaN

                                   mean_uncertainty_std  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)               0.179990
         BEDL_LDL (loglikelihood)              0.136193
         EDL_LDL (bayes_mse)                   0.132507
         BEDL_LDL (bayes_mse)                  0.167301
         AA_BP                                      NaN
         SA_BFGS                                    NaN
         Duo_LDL                                    NaN
         SNEFY_LDL                             0.255769
SBU_3DFE EDL_LDL (loglikelihood)               0.190581
         EDL_LDL (bayes_mse)                   0.270037
         Duo_LDL                                    NaN
         AA_BP                                      NaN
         BEDL_LDL (bayes_mse)                  0.036961
         SA_BFGS                                    NaN
         SNEFY_LDL                             0.110726
         BEDL_LDL (loglikelihood)              0.028451
Movie    EDL_LDL (loglikelihood)               0.016352
         BEDL_LDL (loglikelihood)              0.007140
         EDL_LDL (bayes_mse)                   0.069320
         BEDL_LDL (bayes_mse)                  0.036008
         Duo_LDL                                    NaN
         SA_BFGS                                    NaN
         AA_BP                                      NaN

                                   uncertainty_calibration_mean  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)                      -0.032102
         BEDL_LDL (loglikelihood)                      0.166635
         EDL_LDL (bayes_mse)                           0.117730
         BEDL_LDL (bayes_mse)                         -0.097058
         AA_BP                                              NaN
         SA_BFGS                                            NaN
         Duo_LDL                                            NaN
         SNEFY_LDL                                     0.090531
SBU_3DFE EDL_LDL (loglikelihood)                      -0.107738
         EDL_LDL (bayes_mse)                          -0.215481
         Duo_LDL                                            NaN
         AA_BP                                              NaN
         BEDL_LDL (bayes_mse)                         -0.208179
         SA_BFGS                                            NaN
         SNEFY_LDL                                    -0.144248
         BEDL_LDL (loglikelihood)                      0.209708
Movie    EDL_LDL (loglikelihood)                       0.201623
         BEDL_LDL (loglikelihood)                      0.192564
         EDL_LDL (bayes_mse)                          -0.021030
         BEDL_LDL (bayes_mse)                          0.061763
         Duo_LDL                                            NaN
         SA_BFGS                                            NaN
         AA_BP                                              NaN

                                   uncertainty_calibration_std
dataset  model
SJAFFE   EDL_LDL (loglikelihood)                      0.304317
         BEDL_LDL (loglikelihood)                     0.321181
         EDL_LDL (bayes_mse)                          0.217872
         BEDL_LDL (bayes_mse)                         0.244648
         AA_BP                                             NaN
         SA_BFGS                                           NaN
         Duo_LDL                                           NaN
         SNEFY_LDL                                    0.289638
SBU_3DFE EDL_LDL (loglikelihood)                      0.197330
         EDL_LDL (bayes_mse)                          0.047545
         Duo_LDL                                           NaN
         AA_BP                                             NaN
         BEDL_LDL (bayes_mse)                         0.081333
         SA_BFGS                                           NaN
         SNEFY_LDL                                    0.133996
         BEDL_LDL (loglikelihood)                     0.231979
Movie    EDL_LDL (loglikelihood)                      0.039701
         BEDL_LDL (loglikelihood)                     0.024253
         EDL_LDL (bayes_mse)                          0.060920
         BEDL_LDL (bayes_mse)                         0.069395
         Duo_LDL                                           NaN
         SA_BFGS                                           NaN
         AA_BP                                             NaN

### Compact view: `mean ± std` per metric

In [13]:
def fmt(mean, std):
    if pd.isna(mean):
        return ''
    return f'{mean:.4f} ± {std:.4f}'


compact_rows = []
for (dataset_name, model_name), df in per_model_results.items():
    if df.empty:
        continue
    row = {'dataset': dataset_name, 'model': model_name}
    for col in df.columns:
        row[col] = fmt(df[col].mean(), df[col].std())
    compact_rows.append(row)

compact = pd.DataFrame(compact_rows).set_index(['dataset', 'model'])
compact

                                         chebyshev            clark  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)   0.1196 ± 0.0106  0.4264 ± 0.0267
         BEDL_LDL (loglikelihood)  0.1177 ± 0.0116  0.4182 ± 0.0335
         EDL_LDL (bayes_mse)       0.1204 ± 0.0099  0.4305 ± 0.0257
         BEDL_LDL (bayes_mse)      0.1201 ± 0.0101  0.4293 ± 0.0273
         AA_BP                     0.1193 ± 0.0114  0.4266 ± 0.0275
         SA_BFGS                   0.0877 ± 0.0087  0.3262 ± 0.0278
         Duo_LDL                   0.1195 ± 0.0111  0.4305 ± 0.0282
         SNEFY_LDL                 0.1444 ± 0.0229  0.5545 ± 0.1121
SBU_3DFE EDL_LDL (loglikelihood)   0.1373 ± 0.0027  0.4106 ± 0.0044
         EDL_LDL (bayes_mse)       0.1364 ± 0.0031  0.4123 ± 0.0045
         Duo_LDL                   0.1348 ± 0.0024  0.4173 ± 0.0043
         AA_BP                     0.1350 ± 0.0026  0.4169 ± 0.0036
         BEDL_LDL (bayes_mse)      0.1353 ± 0.0029  0.4148 ± 0.0043
         SA_BFGS                   0.1290 ± 0.0023  0.4039 ± 0.0065
         SNEFY_LDL                 0.1871 ± 0.0408  0.7175 ± 0.2074
         BEDL_LDL (loglikelihood)  0.1286 ± 0.0054  0.3869 ± 0.0137
Movie    EDL_LDL (loglikelihood)   0.1162 ± 0.0027  0.5252 ± 0.0119
         BEDL_LDL (loglikelihood)  0.1180 ± 0.0028  0.5327 ± 0.0112
         EDL_LDL (bayes_mse)       0.1241 ± 0.0050  0.5604 ± 0.0203
         BEDL_LDL (bayes_mse)      0.1181 ± 0.0030  0.5357 ± 0.0115
         Duo_LDL                   0.1194 ± 0.0040  0.5451 ± 0.0167
         SA_BFGS                   0.1451 ± 0.0039  0.5866 ± 0.0100
         AA_BP                     0.1153 ± 0.0033  0.5233 ± 0.0137

                                          canberra    kl_divergence  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)   0.8967 ± 0.0617  0.0737 ± 0.0095
         BEDL_LDL (loglikelihood)  0.8766 ± 0.0791  0.0713 ± 0.0101
         EDL_LDL (bayes_mse)       0.9006 ± 0.0592  0.0740 ± 0.0084
         BEDL_LDL (bayes_mse)      0.8968 ± 0.0653  0.0740 ± 0.0090
         AA_BP                     0.8891 ± 0.0612  0.0737 ± 0.0110
         SA_BFGS                   0.6653 ± 0.0538  0.0432 ± 0.0090
         Duo_LDL                   0.8960 ± 0.0605  0.0741 ± 0.0096
         SNEFY_LDL                 1.1572 ± 0.2326  0.1274 ± 0.0469
SBU_3DFE EDL_LDL (loglikelihood)   0.8967 ± 0.0077  0.0837 ± 0.0016
         EDL_LDL (bayes_mse)       0.8981 ± 0.0088  0.0837 ± 0.0022
         Duo_LDL                   0.9036 ± 0.0074  0.0828 ± 0.0016
         AA_BP                     0.9033 ± 0.0062  0.0828 ± 0.0016
         BEDL_LDL (bayes_mse)      0.9001 ± 0.0092  0.0828 ± 0.0019
         SA_BFGS                   0.8636 ± 0.0115  0.0759 ± 0.0020
         SNEFY_LDL                 1.4511 ± 0.3840  0.2394 ± 0.1413
         BEDL_LDL (loglikelihood)  0.8411 ± 0.0306  0.0738 ± 0.0059
Movie    EDL_LDL (loglikelihood)   1.0025 ± 0.0211  0.0995 ± 0.0036
         BEDL_LDL (loglikelihood)  1.0167 ± 0.0206  0.1024 ± 0.0044
         EDL_LDL (bayes_mse)       1.0652 ± 0.0416  0.1113 ± 0.0094
         BEDL_LDL (bayes_mse)      1.0170 ± 0.0220  0.1024 ± 0.0048
         Duo_LDL                   1.0360 ± 0.0326  0.1138 ± 0.0105
         SA_BFGS                   1.1193 ± 0.0178  0.1331 ± 0.0045
         AA_BP                     0.9990 ± 0.0255  0.0992 ± 0.0046

                                            cosine     intersection  \
dataset  model
SJAFFE   EDL_LDL (loglikelihood)   0.9306 ± 0.0089  0.8473 ± 0.0112
         BEDL_LDL (loglikelihood)  0.9328 ± 0.0099  0.8506 ± 0.0138
         EDL_LDL (bayes_mse)       0.9302 ± 0.0078  0.8466 ± 0.0104
         BEDL_LDL (bayes_mse)      0.9303 ± 0.0085  0.8472 ± 0.0117
         AA_BP                     0.9306 ± 0.0102  0.8484 ± 0.0113
         SA_BFGS                   0.9594 ± 0.0081  0.8882 ± 0.0089
         Duo_LDL                   0.9302 ± 0.0089  0.8472 ± 0.0108
         SNEFY_LDL                 0.8888 ± 0.0364  0.8017 ± 0.0409
SBU_3DFE EDL_LDL (loglikelihood)   0.9189 ± 0.0016  0.8397 ± 0.0015
         EDL_LDL (bayes_mse)       0.9189 ± 0.0020  0.8393 ± 0.0017
         Duo_LDL                   0.9194 ± 0.0015  0.8381 ± 0.0014
         AA_BP                     0.9193 ± 0.0016  0.8382 ± 0.0013
         BEDL_LDL (bayes_mse)      0.9195 ± 0.0018  0.8388 ± 0.0018
         SA_BFGS                   0.9258 ± 0.0018  0.8451 ± 0.0021
         SNEFY_LDL                 0.8349 ± 0.0554  0.7555 ± 0.0542
         BEDL_LDL (loglikelihood)  0.9279 ± 0.0055  0.8493 ± 0.0055
Movie    EDL_LDL (loglikelihood)   0.9345 ± 0.0020  0.8348 ± 0.0028
         BEDL_LDL (loglikelihood)  0.9328 ± 0.0027  0.8322 ± 0.0029
         EDL_LDL (bayes_mse)       0.9271 ± 0.0056  0.8233 ± 0.0076
         BEDL_LDL (bayes_mse)      0.9330 ± 0.0026  0.8323 ± 0.0032
         Duo_LDL                   0.9313 ± 0.0039  0.8295 ± 0.0056
         SA_BFGS                   0.9115 ± 0.0029  0.8074 ± 0.0033
         AA_BP                     0.9348 ± 0.0026  0.8354 ± 0.0038

                                  mean_uncertainty uncertainty_calibration
dataset  model
SJAFFE   EDL_LDL (loglikelihood)   0.4789 ± 0.1800        -0.0321 ± 0.3043
         BEDL_LDL (loglikelihood)  0.3322 ± 0.1362         0.1666 ± 0.3212
         EDL_LDL (bayes_mse)       0.4593 ± 0.1325         0.1177 ± 0.2179
         BEDL_LDL (bayes_mse)      0.2815 ± 0.1673        -0.0971 ± 0.2446
         AA_BP                                 NaN                     NaN
         SA_BFGS                               NaN                     NaN
         Duo_LDL                               NaN                     NaN
         SNEFY_LDL                 0.3008 ± 0.2558         0.0905 ± 0.2896
SBU_3DFE EDL_LDL (loglikelihood)   0.3616 ± 0.1906        -0.1077 ± 0.1973
         EDL_LDL (bayes_mse)       0.3101 ± 0.2700        -0.2155 ± 0.0475
         Duo_LDL                               NaN                     NaN
         AA_BP                                 NaN                     NaN
         BEDL_LDL (bayes_mse)      0.0309 ± 0.0370        -0.2082 ± 0.0813
         SA_BFGS                               NaN                     NaN
         SNEFY_LDL                 0.2411 ± 0.1107        -0.1442 ± 0.1340
         BEDL_LDL (loglikelihood)  0.1652 ± 0.0285         0.2097 ± 0.2320
Movie    EDL_LDL (loglikelihood)   0.2835 ± 0.0164         0.2016 ± 0.0397
         BEDL_LDL (loglikelihood)  0.2365 ± 0.0071         0.1926 ± 0.0243
         EDL_LDL (bayes_mse)       0.1016 ± 0.0693        -0.0210 ± 0.0609
         BEDL_LDL (bayes_mse)      0.0176 ± 0.0360         0.0618 ± 0.0694
         Duo_LDL                               NaN                     NaN
         SA_BFGS                               NaN                     NaN
         AA_BP                                 NaN                     NaN

## Uncertainty results (EDL_LDL, BEDL_LDL, SNEFY_LDL only)

- `mean_uncertainty` — average per-sample uncertainty on test (model-specific
  scale; lower = more confident).
- `uncertainty_calibration` — Spearman ρ between per-sample uncertainty and
  per-sample KL divergence error. Higher = uncertainty better predicts error.

In [14]:
uncertainty_models = {
    'EDL_LDL (loglikelihood)', 'EDL_LDL (bayes_mse)',
    'BEDL_LDL (loglikelihood)', 'BEDL_LDL (bayes_mse)',
    'SNEFY_LDL',
}

uncertainty_rows = []
for (dataset_name, model_name), df in per_model_results.items():
    if model_name not in uncertainty_models or df.empty:
        continue
    if 'mean_uncertainty' not in df.columns:
        continue
    uncertainty_rows.append({
        'dataset': dataset_name,
        'model': model_name,
        'mean_uncertainty':        fmt(df['mean_uncertainty'].mean(),        df['mean_uncertainty'].std()),
        'uncertainty_calibration': fmt(df['uncertainty_calibration'].mean(), df['uncertainty_calibration'].std()),
    })

uncertainty_summary = pd.DataFrame(uncertainty_rows).set_index(['dataset', 'model'])
uncertainty_summary

                                  mean_uncertainty uncertainty_calibration
dataset  model
SJAFFE   EDL_LDL (loglikelihood)   0.4789 ± 0.1800        -0.0321 ± 0.3043
         BEDL_LDL (loglikelihood)  0.3322 ± 0.1362         0.1666 ± 0.3212
         EDL_LDL (bayes_mse)       0.4593 ± 0.1325         0.1177 ± 0.2179
         BEDL_LDL (bayes_mse)      0.2815 ± 0.1673        -0.0971 ± 0.2446
         SNEFY_LDL                 0.3008 ± 0.2558         0.0905 ± 0.2896
SBU_3DFE EDL_LDL (loglikelihood)   0.3616 ± 0.1906        -0.1077 ± 0.1973
         EDL_LDL (bayes_mse)       0.3101 ± 0.2700        -0.2155 ± 0.0475
         BEDL_LDL (bayes_mse)      0.0309 ± 0.0370        -0.2082 ± 0.0813
         SNEFY_LDL                 0.2411 ± 0.1107        -0.1442 ± 0.1340
         BEDL_LDL (loglikelihood)  0.1652 ± 0.0285         0.2097 ± 0.2320
Movie    EDL_LDL (loglikelihood)   0.2835 ± 0.0164         0.2016 ± 0.0397
         BEDL_LDL (loglikelihood)  0.2365 ± 0.0071         0.1926 ± 0.0243
         EDL_LDL (bayes_mse)       0.1016 ± 0.0693        -0.0210 ± 0.0609
         BEDL_LDL (bayes_mse)      0.0176 ± 0.0360         0.0618 ± 0.0694

## Shut down the pool

In [15]:
executor.shutdown(wait=True, kill_workers=True)